name: Develop
on:
  push:
    branches:
      - develop
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ github.head_ref }} <- develop"
          body: |
            This is an automated pull request to merge the changes from the feature branch to the development branch.
          branch: develop
          base: ${{ github.head_ref }}
          labels: automated-pr
          delete-branch: true
          commit-message: ":alien: ci: automated change"