name: Develop
on:
  pull_request:
    types: closed
    branches:
      - develop
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          create_annotated_tag: true
          pre_release_branches: "none"
          tag_prefix: v
      - name: Create Branch
        run: |
          BRANCH_NAME="release/${{ steps.tag_version.outputs.new_tag }}"
          COMMIT_SHA=$(gh api /repos/${{github.repository}}/branches/main --jq '.commit.sha')

          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{github.repository}}/git/refs \
          -f "ref=refs/heads/${BRANCH_NAME}" -f "sha=${COMMIT_SHA}"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create Pull Request
        run: |
          gh pr create --base release/${{ steps.tag_version.outputs.new_tag }} --head develop \
          --title "release/${{ steps.tag_version.outputs.new_tag }} <- develop" \
          --body "
          ## 🚀 Release Candidate ${{ steps.tag_version.outputs.new_tag }}
          Este PR automatizado mescla as alterações da branch \`develop\` na branch \`release/${{ steps.tag_version.outputs.new_tag }}\`.

          ## 🔧 Alterações
          ${{ steps.tag_version.outputs.changelog }}

          ## ✅ Checklist
          - [ ] Código revisado
          - [ ] Testes aprovados
          - [ ] Documentação atualizada

          🔄 *PR gerado automaticamente pelo CI/CD.*
          " \
          --label "automated"
        env:
          GH_TOKEN: ${{ github.token }}
