name: Open Pull Request to Development
on:
  push:
    branches:
      - feature/*
      - fix/*
jobs:
  open-pr-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: true
      - name: Run Linter
        run: pnpm run lint
      - name: Create Pull Request
        run: |
          gh pr create --base develop --head ${{ github.ref_name }} \
          --title "develop <- ${{ github.ref_name }}" \
          --body "
          ## 🚀 Descrição
          Este PR automatizado mescla as alterações da branch \`${{ github.ref_name }}\` na branch \`develop\`.

          ## 🔧 Alterações
          - Descreva as principais mudanças aqui.

          ## ✅ Checklist
          - [ ] Código revisado
          - [ ] Testes aprovados
          - [ ] Documentação atualizada

          🔄 *PR gerado automaticamente pelo CI/CD.*
          " \
          --label "automated"
        env:
          GH_TOKEN: ${{ github.token }}
